language: python
#cache: pip

#addons: 
#  rethinkdb: '2.3.5'

python: 3.5
        #- 3.4

#env:
  #- TOXENV=py34-rdb
  #- TOXENV=py35-rdb
    #- TOXENV=py34-mdb
    #- TOXENV=py35-mdb
    #- TOXENV=flake8
    #- TOXENV=docsroot
    #- TOXENV=docsserver

#matrix:
        #  fast_finish: true
        #allow_failures:
        #- env: BIGCHAINDB_DATABASE_BACKEND=mongodb
    #exclude:
          #- python: 3.4 
          #env: TOXENV=flake8 
# - python: 3.4 
#    env: TOXENV=docsroot
#  - python: 3.4 
#    env: TOXENV=docsserver
#  include:
#  - python: 3.4
#    services: mongodb
#    env: BIGCHAINDB_DATABASE_BACKEND=mongodb
#  - python: 3.4
#    addons: 
#      rethinkdb: '2.3.5'
#    env: BIGCHAINDB_DATABASE_BACKEND=rethinkdb
#  - python: 3.5
#    services: mongodb
#    env: BIGCHAINDB_DATABASE_BACKEND=mongodb
#  - python: 3.5
#    addons: 
#      rethinkdb: '2.3.5'
#    env: BIGCHAINDB_DATABASE_BACKEND=rethinkdb

before_install: sudo .ci/travis-before-install.sh
#  - sudo apt-get update -qq

#install: .ci/travis-install.sh
install: 
    - pip install --upgrade pip
    - pip install -e .[test]
    - pip install --upgrade codecov

#before_script: .ci/travis-before-script.sh

#script: tox -e ${TOXENV}
script: .ci/travis_script.sh

after_success: .ci/travis-after-success.sh
