sudo: required

dist: trusty

services:
  - docker

language: python
cache: pip

python:
  - 3.6

env:
  - TOXENV=flake8
  - TOXENV=docsroot
  - TOXENV=docsserver

matrix:
  fast_finish: true
  include:
  - python: 3.6
    env:
    - BIGCHAINDB_DATABASE_BACKEND=localmongodb
    - BIGCHAINDB_DATABASE_SSL=

before_install: sudo .ci/travis-before-install.sh

install: .ci/travis-install.sh

before_script: .ci/travis-before-script.sh

script: .ci/travis_script.sh

after_success: .ci/travis-after-success.sh
