language: python
cache: pip

python:
  - 3.4
  - 3.5

env:
  - TOXENV=flake8
  - TOXENV=docsroot
  - TOXENV=docsserver

matrix:
  fast_finish: true
  allow_failures:
  - env: BIGCHAINDB_DATABASE_BACKEND=mongodb
  exclude:
  - python: 3.4 
    env: TOXENV=flake8 
  - python: 3.4 
    env: TOXENV=docsroot
  - python: 3.4 
    env: TOXENV=docsserver
  include:
  - python: 3.4
    addons: 
      rethinkdb: '2.3.5'
    env: BIGCHAINDB_DATABASE_BACKEND=rethinkdb
  - python: 3.5
    services: mongodb
    env: BIGCHAINDB_DATABASE_BACKEND=mongodb
  - python: 3.5
    addons: 
      rethinkdb: '2.3.5'
    env: BIGCHAINDB_DATABASE_BACKEND=rethinkdb

before_install: sudo .ci/travis-before-install.sh

install: .ci/travis-install.sh

script: .ci/travis_script.sh

after_success: .ci/travis-after-success.sh
