version: '3'

services:

  #############################################################################
  #                                                                           #
  #                                 NODE 1                                    #
  #                                                                           #
  #############################################################################
  mdb-one:
    image: mongo:3.4.3
    ports:
      - "27017"
    command: mongod
  bdb-one:
    depends_on:
      - mdb-one
    build:
      context: .
      dockerfile: ./compose/abci/Dockerfile
      args:
        backend: localmongodb
    volumes:
      - ./bigchaindb:/usr/src/app/bigchaindb
      - ./tests:/usr/src/app/tests
    environment:
      BIGCHAINDB_DATABASE_BACKEND: localmongodb
      BIGCHAINDB_DATABASE_HOST: mdb-one
      BIGCHAINDB_DATABASE_PORT: 27017
      BIGCHAINDB_SERVER_BIND: 0.0.0.0:9984
      BIGCHAINDB_WSSERVER_HOST: 0.0.0.0
      TENDERMINT_HOST: tendermint-one
      TENDERMINT_PORT: 46657
    ports:
      - "9984"
    command: bigchaindb -l DEBUG start --init
  tendermint-one:
    image: tendermint/tendermint
    volumes:
      - ./network/node1:/tendermint
    entrypoint: ''
    command: bash -c "tendermint unsafe_reset_all && tendermint --log_level debug node"


  #############################################################################
  #                                                                           #
  #                                 NODE 2                                    #
  #                                                                           #
  #############################################################################
  mdb-two:
    image: mongo:3.4.3
    ports:
      - "27017"
    command: mongod
  bdb-two:
    depends_on:
      - mdb-two
    build:
      context: .
      dockerfile: ./compose/abci/Dockerfile
      args:
        backend: localmongodb
    volumes:
      - ./bigchaindb:/usr/src/app/bigchaindb
      - ./tests:/usr/src/app/tests
    environment:
      BIGCHAINDB_DATABASE_BACKEND: localmongodb
      BIGCHAINDB_DATABASE_HOST: mdb-two
      BIGCHAINDB_DATABASE_PORT: 27017
      BIGCHAINDB_SERVER_BIND: 0.0.0.0:9984
      BIGCHAINDB_WSSERVER_HOST: 0.0.0.0
      TENDERMINT_HOST: tendermint-two
      TENDERMINT_PORT: 46657
    ports:
      - "9984"
    command: bigchaindb -l DEBUG start --init
  tendermint-two:
    image: tendermint/tendermint
    volumes:
      - ./network/node2:/tendermint
    entrypoint: ''
    command: bash -c "tendermint unsafe_reset_all && tendermint --log_level debug node"


  #############################################################################
  #                                                                           #
  #                                 NODE 3                                    #
  #                                                                           #
  #############################################################################
  mdb-three:
    image: mongo:3.4.3
    ports:
      - "27017"
    command: mongod
  bdb-three:
    depends_on:
      - mdb-three
    build:
      context: .
      dockerfile: ./compose/abci/Dockerfile
      args:
        backend: localmongodb
    volumes:
      - ./bigchaindb:/usr/src/app/bigchaindb
      - ./tests:/usr/src/app/tests
    environment:
      BIGCHAINDB_DATABASE_BACKEND: localmongodb
      BIGCHAINDB_DATABASE_HOST: mdb-three
      BIGCHAINDB_DATABASE_PORT: 27017
      BIGCHAINDB_SERVER_BIND: 0.0.0.0:9984
      BIGCHAINDB_WSSERVER_HOST: 0.0.0.0
      TENDERMINT_HOST: tendermint-three
      TENDERMINT_PORT: 46657
    ports:
      - "9984"
    command: bigchaindb -l DEBUG start --init
  tendermint-three:
    image: tendermint/tendermint
    volumes:
      - ./network/node3:/tendermint
    entrypoint: ''
    command: bash -c "tendermint unsafe_reset_all && tendermint --log_level debug node"


  #############################################################################
  #                                                                           #
  #                                 NODE 4                                    #
  #                                                                           #
  #############################################################################
  mdb-four:
    image: mongo:3.4.3
    ports:
      - "27017"
    command: mongod
  bdb-four:
    depends_on:
      - mdb-four
    build:
      context: .
      dockerfile: ./compose/abci/Dockerfile
      args:
        backend: localmongodb
    volumes:
      - ./bigchaindb:/usr/src/app/bigchaindb
      - ./tests:/usr/src/app/tests
    environment:
      BIGCHAINDB_DATABASE_BACKEND: localmongodb
      BIGCHAINDB_DATABASE_HOST: mdb-four
      BIGCHAINDB_DATABASE_PORT: 27017
      BIGCHAINDB_SERVER_BIND: 0.0.0.0:9984
      BIGCHAINDB_WSSERVER_HOST: 0.0.0.0
      TENDERMINT_HOST: tendermint-four
      TENDERMINT_PORT: 46657
    ports:
      - "9984"
    command: bigchaindb -l DEBUG start --init
  tendermint-four:
    image: tendermint/tendermint
    volumes:
      - ./network/node4:/tendermint
    entrypoint: ''
    command: bash -c "tendermint unsafe_reset_all && tendermint --log_level debug node"


  #############################################################################
  #############################################################################
  #############################################################################
  #
  # clients
  #
  #############################################################################
  #############################################################################
  #############################################################################
  curl-client:
    image: appropriate/curl
    command: /bin/sh -c "curl http://tendermint-one:46657/abci_query && curl http://bdb-one:9984/"
  driver:
    build:
      context: .
      dockerfile: ./compose/driver/Dockerfile
