version: '3'

services:
  mdb:
    image: mongo:3.4.3
    ports:
      - "27017"
    command: mongod
  bdb:
    depends_on:
      - mdb
    build:
      context: .
      dockerfile: ./compose/travis/Dockerfile
      args:
        backend: localmongodb
    volumes:
      - .:/usr/src/app/
    environment:
      BIGCHAINDB_DATABASE_BACKEND: localmongodb
      BIGCHAINDB_DATABASE_HOST: mdb
      BIGCHAINDB_DATABASE_PORT: 27017
      BIGCHAINDB_SERVER_BIND: 0.0.0.0:9984
      BIGCHAINDB_WSSERVER_HOST: 0.0.0.0
      BIGCHAINDB_START_TENDERMINT: 0
      TENDERMINT_HOST: tendermint
      TENDERMINT_PORT: 46657
      # TODO move into dedicated docker-compose travis file
      #COVERAGE_FILE: tests/.coverage
    ports:
      - "9984"
      - "46658:46658"
    command: bigchaindb -l DEBUG start
  tendermint:
    depends_on:
      - bdb
    image: tendermint/tendermint:0.13
    volumes:
      - ./tmdata/config.toml:/tendermint/config.toml
    entrypoint: ''
    ports:
      - "46656:46656"
      - "46657:46657"
    command: bash -c "tendermint init && tendermint node"
