version: '3'

services:
  mdb:
    image: mongo:3.4.3
    ports:
      - "27017"
    command: mongod --replSet=bigchain-rs
  bdb-abci:
    depends_on:
      - mdb
    build:
      context: .
      dockerfile: ./compose/abci/Dockerfile
      args:
        backend: mongodb
    volumes:
      - .:/usr/src/app/
    environment:
      BIGCHAINDB_DATABASE_BACKEND: mongodb
      BIGCHAINDB_DATABASE_HOST: mdb
      BIGCHAINDB_DATABASE_PORT: 27017
      BIGCHAINDB_SERVER_BIND: 0.0.0.0:9984
      BIGCHAINDB_WSSERVER_HOST: 0.0.0.0
    ports:
      - "9984"
    #command: python lab/counter.py
    command: bigchaindb start --init
  tendermint:
    image: tendermint/tendermint
    volumes:
      - ./tmdata:/tendermint
    entrypoint: ''
    #command: ['tendermint', '--log_level', 'debug', 'node']
    command: bash -c "tendermint unsafe_reset_all && tendermint --log_level debug node"
  curl-client:
    image: appropriate/curl
    command: /bin/sh -c "curl http://tendermint:46657/abci_query && curl http://bdb-abci:9984/"
  driver:
    build:
      context: .
      dockerfile: ./compose/driver/Dockerfile
